### ISSUE TITLE
Richtext Styles Not being Applied

### ISSUE THREAD

**Issue by HolyChute** [elapouya/python-docx-template#65] opened 2017-02-04 20:41 UTC
Hi, just wanted to say that your lib is fantastic, but i appear to be having an issue. It appears that if the style contains a space or certain characters, the style isnt applied in the output file. I was just wondering if there was a work around for this? Many Thanks. Example below:
`rt.add(tag.text , style='Subtle Reference')`

**Comment by elapouya** [comment] 2017-02-07 09:23
Could you try the style by removing spaces : 'Subtle Reference' -> 'SubtleReference'
and another try without uppercases -> 'subtlereference'

**Comment by HolyChute** [comment] 2017-02-07 21:21
Hey, thanks for the reply. Just wondering if you're referring to changing it within the python code or template styles? The template being used is kind of out of my control

**Comment by elapouya** [comment] 2017-02-08 08:40
In your python code

**Comment by HolyChute** [comment] 2017-02-09 17:33
Hi again, apologies for the late response. Unfortunately neither work

**Comment by elapouya** [comment] 2017-02-09 18:21
Could you give the docx template and the python code you are using

2017-02-09 18:33 GMT+01:00 HolyChute <notifications@github.com>:

**Comment by HolyChute** [comment] 2017-02-10 10:44
https://stackoverflow.com/questions/42143575/how-to-apply-word-styles-to-richtext-object-docxtpl-library
Sure, uploaded it here just for ease

**Comment by elapouya** [comment] 2017-02-10 10:49
Your template.docx is not uploaded : I need it to examine the xml code for
styles with spaces.
When I do tests my side, I do not have spaces in xml code...

2017-02-10 11:44 GMT+01:00 HolyChute <notifications@github.com>:

**Comment by HolyChute** [comment] 2017-02-12 22:00
[template.docx](https://github.com/elapouya/python-docx-template/files/769687/template.docx)

**Comment by elapouya** [comment] 2017-02-12 23:09
On my MSWord 2007, I cannot see the style 'Subtle Reference' in the available styles for your template.docx. so I cannot do some testing : 
Could you give me a .docx where you have some text having the style 'Subtle Reference' ?

**Comment by HolyChute** [comment] 2017-02-13 10:06
[template.docx](https://github.com/elapouya/python-docx-template/files/770701/template.docx)

**Comment by elapouya** [comment] 2017-02-13 11:52
```
In [1]: from docxtpl import *

In [2]: r=R('I am test data',style='SubtleReference')

In [3]: str(r)
Out[3]: '<w:r><w:rPr><w:rStyle w:val="SubtleReference"/></w:rPr><w:t xml:space="preserve">I am test data</w:t></w:r>'
```

This correspond to the xml code from template.docx given with the style manually applied
At first sight I would say that removing spaces should work.
But it seems not for you : I have to investiguate...

**Comment by elapouya** [comment] 2017-02-13 11:57
Question : is "Subtle Reference" a predefined style inside MSWord ?

**Comment by HolyChute** [comment] 2017-02-13 17:18
It is yeah, i thought i'd use a pre-defined one first and see if i could get that working before moving onto the more complex ones i have to use (e.g "Table(Findings detail)-bullet level 2)" )

**Comment by elapouya** [comment] 2017-02-13 18:38
it seems that predefined style are a little tricky : when I load your latest template.docx and then re-save it as xml, the style is now 'Rfrenceple'.
I think, the only way to workaround the issue is to create a custom style...

**Comment by HolyChute** [comment] 2017-02-15 12:13
The above pre-defined template was only used as an example and the issue still persists when using custom styles such as 'Table(Findings detail)-bullet level 2'. i've attached the new template doc to include this style.

ps. just out of curiosity will you be adding a built-in option for bullet points (like you already have with bold, italic etc)? I've looked at the xml for this and i believe it is just '<w:pStyle w:val="ListParagraph"/>'
[template.docx](https://github.com/elapouya/python-docx-template/files/776972/template.docx)

**Comment by elapouya** [comment] 2017-02-22 09:33
please could you open an issue for bullet points enhancement

**Comment by elapouya** [comment] 2017-06-20 22:35
The only solution I see is to create custom style without space in the name in your docx template.
I close this issue.

**Closed by elapouya** 2017-06-20 22:35 UTC
