### ISSUE TITLE
Error: lxml.etree.XMLSyntaxError: <no detail available>

### ISSUE THREAD

**Issue by ravshan4yk** [elapouya/python-docx-template#118] opened 2018-05-17 11:03 UTC
Hello!
Need help, please. I get an error when I generate a word document:
```Traceback (most recent call last):
  File "/payments/venv/lib/python3.4/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/payments/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/payments/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/payments/venv/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/payments/venv/lib/python3.4/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/payments/src/payments/views.py", line 98, in get
    'merchant': '123456',
  File "/payments/venv/lib/python3.4/site-packages/docxtpl/__init__.py", line 151, in render
    tree = self.fix_tables(xml_src)
  File "/payments/venv/lib/python3.4/site-packages/docxtpl/__init__.py", line 166, in fix_tables
    tree = etree.fromstring(xml)
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1757, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1067, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 600, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 710, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 650, in lxml.etree._raiseParseError
  File "<string>", line 0
lxml.etree.XMLSyntaxError: <no detail available>
```
My code:
```        
doc = DocxTemplate('tpl.docx'))
doc.render({
    'merchant': '123456',
})
doc.save('output.docx')
```
My word tpl.docx contains string:
```
Hi {{merchant}}
```

**Comment by ravshan4yk** [comment] 2018-05-17 12:29
I used versions 0.4.7 and 0.4.10. I got the same errors.
My file: [tpl.docx](https://github.com/elapouya/python-docx-template/files/2013135/tpl.docx)

**Comment by elapouya** [comment] 2018-05-17 12:56
Your template works for me with python 3.6.3

pip freeze says :

docxtpl==0.4.10
Jinja2==2.10
lxml==4.2.1
MarkupSafe==1.0
python-docx==0.8.6
six==1.11.0

What's about you ?

**Comment by ravshan4yk** [comment] 2018-05-17 13:07
My python version 3.4.7

pip freeze:

docxtpl==0.4.10
Jinja2==2.10
lxml==4.2.1
MarkupSafe==1.0
python-docx==0.8.6
six==1.10.0

**Comment by elapouya** [comment] 2018-05-17 13:12
The only difference is python version... Could you try with python 3.6 ?
How did you install lxml ?

**Comment by ravshan4yk** [comment] 2018-05-17 13:54
lxml is dependency python-docx-template and install with command `pip install docxtpl`
I tried with python 3.5 and get the same error.

**Comment by ravshan4yk** [comment] 2018-05-18 05:33
Hi, I have 2 mashines on Linux.
But first mashine has python 3.4.7 and I get this error. Second mashine has python 3.5, python 3.4.3 and my script work good.
I can't understand what the problem is.

**Comment by elapouya** [comment] 2018-05-18 07:07
I am sorry, but I have no other idea.
I am closing this issue as not reproductible for me.

**Closed by elapouya** 2018-05-18 07:07 UTC

**Comment by ravshan4yk** [comment] 2018-05-23 11:52
I solved this problem.
I reinstalled lib **lxml** with command:

`pip install --no-binary lxml -U --force-reinstall lxml`

Now it works good.
