### ISSUE TITLE
Regular expression in patch_xml problem - removing spaces in front of a tag

### ISSUE THREAD

**Issue by naro** [elapouya/python-docx-template#82] opened 2017-05-26 11:38 UTC
Let's have the following DOCX template:
```
Available answers:
    {% for answer in answers %}{{ answer.letter }} {{r answer.text }}
    {% endfor %}
```
which generates a XML like this:
```
<w:r><w:rPr><w:b w:val="false"/><w:bCs w:val="false"/><w:sz w:val="16"/><w:szCs w:val="16"/></w:rPr><w:t xml:space="preserve"> {{r answer.text }}</w:t></w:r>
```

The regular expression in patch_xml
```
<w:r[ >](?:(?!<w:r[ >]).)*({%|{{)r ([^}%]*(?:%}|}})).*?</w:r>
```
eats the initial space in front of ```{{r answer.text }}``` tag so in the rendered output the "letter" and "text" does not have any space in between.
Expected output of the regex would not be  "{{ answer.text }}" but " {{ answer.text }}".

See the following regex101 code: https://regex101.com/r/aUJ0w1/1/

Have you any idea how to fix this, please?

**Comment by elapouya** [comment] 2017-06-20 22:28
Duplicate of the #81

**Closed by elapouya** 2017-06-20 22:28 UTC
